version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tempdb
    ports:
      - "5434:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
